---
title: Final Project 527"
author: "Satoshi Ido, Shu-Ming Meng, Robert Jung"
date: 16 April 2023
output: pdf_document
---
```{r setup, include = FALSE, cache = FALSE}
knitr::opts_chunk$set(
    echo = TRUE,
    warning = FALSE,
    message = FALSE)
```

# library
```{r}
library("MASS")
library("lmtest")
library("dplyr")
library("data.table")
library("stringi")
library("openxlsx")
library("ggplot2")
library("lattice")
library("epiDisplay")
library("car")
library("treemap")
library("d3treeR")
library("htmlwidgets")
```

# import the dataset
```{r}
print(getwd())
df <- read.csv("/Users/satoshiido/Documents/statistical-analysis/527/unicorn_data.csv")
head(df, 3)
```

# preprocess
clean the data
```{r}
cleaner <- function(x){
    # delete the unncessary columns
    x <- subset(
        x,
        select = -c(
            Investors, Portfolio.Exits, Entrepreneur,
            Final.Degree, Final.School)
        )
    # remove the $ and M signs and convert character into numeric
    FUN <- function(y){
            stri_replace_all_regex(y, pattern = c("[$]", "[M]"),
            replacement = c("", ""), vectorize = FALSE)
            }
    cols = c("Valuation.Billion", "Total.Raised.Million")
    x[, cols] <- lapply(x[, cols], FUN)
    x %>% mutate_at(cols, as.numeric) -> x
    # change string to date format
    x$Date.Joined <- as.Date(x$Date.Joined, format = "%m/%d/%Y")
    # return the list of Investors given delimited strings
    x$Select.Inverstors <- strsplit(x$Select.Inverstors, split = ", ")
    return(x)
    }

df <- cleaner(df)
```


# Visualization

## tree map by country and industry
```{r}
# basic treemap
p <- treemap(df,
            index = c("Country", "Industry", "Company"),
            type = "index",
            vSize = "Valuation.Billion",
            fontcolor.labels = c("white", "white"),
            fontsize.title = 14,
            fontsize.labels = c(12, 9, 8),
            palette = "Set2",
            bg.labels = c("transparent"),
            align.labels = list(
              c("left", "top"),
              c("right", "bottom"),
              c("center", "center")
            ),
            border.col = c("black", "black", "black"),
            border.lwds = c(4, 2, 1),
            title = "Valuation by Country&Industry",
            overlap.labels = 0,
            inflate.labels = F
        )
p
# make it interactive ("rootname" becomes the title of the plot):
# inter <- d3tree2(p,  rootname = "Valuation by Country&Industry")

# save the widget
# saveWidget(inter, file = paste0(getwd(), "/527/treemap.html"))
```

## top 5 countries
```{r}
# group by country and count the number of each country
tmp <- df %>%
    group_by(Country) %>%
    summarise(total.country.count = n(), .groups = "drop")
# pick the top 5 countries which produce the unicorn the most
top5countries <- unlist(tmp[order(tmp$total.country.count, decreasing = TRUE), ][0:5, 1])
tmp <- df[which(df$Country %in% top5countries), ] %>%
    group_by(Country) %>%
    summarise(total.value.Billion = sum(Valuation.Billion), .groups = "drop") %>%
    as.data.frame()

# plot
ggplot(
        tmp,
        aes(x = reorder(Country, -total.value.Billion),
        y = total.value.Billion)) +
    geom_bar(stat = "identity", fill = "skyblue4") +
    labs(
        title = "Top 5 countries producing unicorn companies values",
        x = "Country",
        y = "Total.value(B)") +
    theme(
        plot.title = element_text(size = 12, hjust = 0.5, color = "gray25"),
        axis.title.x = element_text(size = 10, hjust = 0.5, color = "gray25"),
        axis.title.y = element_text(size = 10, hjust = 0.5, color = "gray25")
        )

```

## top 10 cities
```{r}
# group by city and count the number of each city
tmp <- df %>%
    group_by(City) %>%
    summarise(total.city.count = n(), .groups = "drop")
# pick the top 10 cities which produce the unicorn the most
top10cities <- unlist(tmp[order(tmp$total.city.count, decreasing = TRUE), ][0:10, 1])
tmp <- df[which(df$City %in% top10cities), ] %>%
    group_by(City) %>%
    summarise(total.value.Billion = sum(Valuation.Billion), .groups = "drop") %>%
    as.data.frame()

# plot
ggplot(
        tmp,
        aes(x = reorder(City, -total.value.Billion),
        y = total.value.Billion)) +
    geom_bar(stat = "identity", fill = "skyblue4") +
    labs(
        title = "Top 10 cities producing unicorn companies values",
        x = "City",
        y = "Total.value(B)") +
    theme(
        plot.title = element_text(size = 12, hjust = 0.5, color = "gray25"),
        axis.title.x = element_text(size = 10, hjust = 0.5, color = "gray25"),
        axis.title.y = element_text(size = 10, hjust = 0.5, color = "gray25"),
        axis.text.x = element_text(size = 8, angle = 60, vjust = 0.7, hjust = 0.7)
        )

```

## Founded year
```{r}
# barchart
barplot(table(df$Founded.Year))
```

## Industry
```{r}
# frequency barchart
tab1(df$Industry, cum.percent = TRUE)
```


## Industries' valuation
```{r}
# divide into subgroup
# Growing IND
growing_list <- c("Artificial Intelligence", "Cybersecurity",
        "Data management & analytics", "Edtech", "Fintech",
        "E-commerce & direct-to-consumer"
        )
df_GI <- df[which(df$Industry %in% growing_list), ]

# Legacy IND
legacy_list <- c("Auto & transportation","Consumer & retail","Hardware",
            "Health","Supply chain, logistics, & delivery","Travel",
            "Internet software & services","Mobile & telecommunications"
            )
df_LI <- df[which(df$Industry %in% legacy_list), ]
```

```{r}
# plotting
boxplot(Valuation.Billion~Industry,
        data=df_LI,
        main="Legacy Industries' Valuation",
        col="orange",
        border="brown"
)

boxplot(Valuation.Billion~Industry,
        data=df_GI,
        main="Growing Industries' Valuation",
        col="orange",
        border="brown"
)
```

```{r}
df$Count <- rep(1,length(df$Company))
barplot(sort(count(df$Country)$freq[which(count(df$Country)$freq>3)])~count(df$Country)$x[which(count(df$Country)$freq>3)],
        main="Number of Unicorn Companies in each Country",
        xlab = "Countries",
        ylab = "Number of Unicorn Companies")
```

```{r}
ggplot(data=df_GI, aes(x=Country, y=Deal.Terms, fill=Industry))+geom_bar(position = "stack", stat="identity")+theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1))
ggplot(data=df_LI, aes(x=Country, y=Deal.Terms, fill=Industry))+geom_bar(position = "stack", stat="identity")+theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1))
```

# Investors
```{r}
# count the number of unicorn startups each investor has invested
# create the matrix of investors frequency count
words.freq <- table(unlist(df$Select.Inverstors))
investors <- cbind(names(words.freq), as.integer(words.freq))
investors <- as.data.frame(investors)
investors$V2 <- as.numeric(investors$V2)
colnames(investors) <- c("investors", "count")
investors <- investors[order(investors$count, decreasing = TRUE), ]
head(investors, 3)


options(repr.plot.width=15, repr.plot.height=8)
investors2 <- filter(investors, count > 20)
ggplot(data = investors2, aes(x = reorder(investors, -count), y = count)) + 
  geom_bar(stat = "identity") +
  theme(axis.text.x = element_text(angle = 75, vjust = 1, hjust = 1))
```


# Other visualization
## 1.industry vs founded year
```{r}
df$Count <- rep(1, length(df$Company))

ggplot(
    data=df, aes(x=Founded.Year, y=Count, fill=Industry))+
    geom_bar(position = "stack", stat="identity")+
    theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1))

ggplot(
    data=df_GI,
    aes(x=Founded.Year, y=Valuation.Billion, fill=Industry))+
    geom_bar(position = "stack", stat="identity")+
    theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1)
    )

ggplot(
    data=df_LI,
    aes(x=Founded.Year, y=Valuation.Billion, fill=Industry))+
    geom_bar(position = "stack", stat="identity")+
    theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1)
    )
```


## 5.Valuation vs total.raised
```{r}
# scatter plot
## Growing IND
plot(y = df_GI[(df_GI$Valuation.Billion > 5) & ((df_GI$Valuation.Billion < 90)), ]$Valuation.Billion,
     x = df_GI[(df_GI$Valuation.Billion > 5) & ((df_GI$Valuation.Billion < 90)), ]$Total.Raised.Million,
        pch = 40,
        col = factor(df_GI$Industry),
        xlab = "Investors.Count",
        ylab = "Valuation.Billion"
        )
```

# modeling
## data preprocess
```{r}
# Country
## group by country and count the number of each country
tmp <- df %>%
    group_by(Country) %>%
    summarise(total.country.count = n(), .groups = "drop")
topcountries.list <- unlist(tmp[tmp$total.country.count > 5, ][,1])

# city
## group by city and count the number of each city
tmp <- df %>%
    group_by(City) %>%
    summarise(total.city.count = n(), .groups = "drop")
topcities.list <- unlist(tmp[tmp$total.city.count > 10, ][,1])
### if the country produces more than 5 companies, it will be 1

# Add a Column to a Dataframe
df2 <- df %>%
        mutate(Country.label = if_else(
                Country %in% topcountries.list, 1, 0
        )) %>%
        mutate(City.label = if_else(
                City %in% topcities.list, 1, 0
        ))

head(df2, 2)

# pick the top 5 countries which produce the unicorn the most
top5countries <- unlist(tmp[order(tmp$total.country.count, decreasing = TRUE), ][0:5, 1])
tmp <- df[which(df$Country %in% top5countries), ] %>%
    group_by(Country) %>%
    summarise(total.value.Billion = sum(Valuation.Billion), .groups = "drop") %>%
    as.data.frame()
```