---
title: "HW1"
author: "Satoshi Ido"
date: 17 January 2024
output: pdf_document
header-includes:
  - "\\usepackage{listings}"
  - "\\lstset{breaklines=true,breakatwhitespace=true}"
---

```{r setup, include = FALSE, cache = FALSE}
knitr::opts_chunk$set(
  echo = TRUE,
  warning = FALSE,
  message = FALSE,
  tidy = TRUE
)
```

```{r}
library("ggplot2")
library("tidyverse")
library("MASS")
library("broom")
library("car")
```

```{r warning=FALSE, message=FALSE, include=FALSE}
# Create the input_dir (input directory)
INPUT_DIR <- "/Users/satoshiido/Documents/programming/statistical-analysis/582/hw1/data"

# If INPUT_DIR has not been created yet, create it
if (!dir.exists(INPUT_DIR)) {
  dir.create(INPUT_DIR)
}

# Create the output_dir (output directory)
OUTPUT_DIR <- "/Users/satoshiido/Documents/programming/statistical-analysis/582/hw1/output"

# If OUTPUT_DIR has not been created yet, create it
if (!dir.exists(OUTPUT_DIR)) {
  dir.create(OUTPUT_DIR)
}

# Read CSV files using a function to specify the directory automatically
read_csv <- function(name, ...) {
  path <- file.path(INPUT_DIR, paste0(name, ".csv"))
  print(paste("Load:", path))
  return(read.csv(path, ...))
}
```

```{r warning=FALSE, message=FALSE}
# read data
df <- read_csv("diesel")
colnames(df) <- c("run", "speed_rpm", "load_lb", "alchol_percent", "injection_timing", "ignition_delay_Cao", "temp_oR", "pressure_psi")
head(df)
is.character(df$injection_timing)
```

```{r warning=FALSE, message=FALSE}
# create a historgram
hist(df$ignition_delay_Cao, main = "Histogram of Ignition Delay", xlab = "Ignition Delay", col = "grey", border = "black")

# count the number of levels in speed_rpm
value_counts <- df %>% count(speed_rpm)
print(value_counts)

# count the number of levels in load_lb
value_counts <- df %>% count(load_lb)
print(value_counts)

# count the number of levels in alchol_percent
value_counts <- df %>% count(alchol_percent)
print(value_counts)
# Create a histogram
hist(df$alchol_percent, main = "Histogram of Alcohol Percent", xlab = "Alcohol Percent", col = "grey", border = "black")

# count the number of levels in injection_timing
value_counts <- df %>% count(injection_timing)
print(value_counts)

# count the number of levels in temp_oR
temp_oR <- df %>% count(temp_oR)
print(temp_oR)
```

qqplot or histogram to check normality of `ignition_delay_Cao`
```{r warning=FALSE, message=FALSE}
hist(df$ignition_delay_Cao, main = "Histogram of Ignition Delay", xlab = "Ignition Delay", col = "grey", border = "black")
```

scatter plot of `speed_rpm` vs `alchol_percent`
```{r warning=FALSE, message=FALSE} 
ggplot(df, aes(x = speed_rpm, y = alchol_percent)) +
  geom_point() +
  geom_smooth(method = "lm", se = FALSE, color = "red") +
  theme_minimal() +
  labs(title = "Scatter Plot of speed_rpm vs alchol_percent", x = "speed_rpm", y = "alchol_percent")
```

interaction plot of `speed_rpm` and `load_lb` on `ignition_delay_Cao`
```{r warning=FALSE, message=FALSE}
df$load_lb_factor <- as.factor(df$load_lb)
df$speed_rpm_factor <- as.factor(df$speed_rpm)
interaction.plot(df$load_lb_factor, df$speed_rpm_factor, df$ignition_delay_Cao, type="b", 
                 xlab="Load (lb)", ylab="Ignition Delay (Cao)", trace.label = "Speed (rpm)",
                 main="Interaction Plot of Load and Ignition Delay")
```

```{r warning=FALSE, message=FALSE}
# Create a scatter plot
plot(df$temp_oR, df$ignition_delay_Cao, main="Scatter Plot of temp_oR vs ignition_delay_Cao", 
     xlab="temp_oR", ylab="ignition_delay_Cao")

# Calculate the correlation coefficient
cor(df$temp_oR, df$ignition_delay_Cao)
```

# modeling
```{r warning=FALSE, message=FALSE}
# fit a linear model
m0 <- lm(ignition_delay_Cao ~ speed_rpm + load_lb + alchol_percent + injection_timing, data = df)
summary(m0)
anova(m0)
```

```{r warning=FALSE, message=FALSE}
vif(m0)
plot(m0, which = 1) # Residuals vs Fitted
plot(m0, which = 2) # Normal Q-Q
plot(m0, which = 3) # Scale-Location
plot(m0, which = 5) # Residuals vs Leverage
```