---
title: "STAT 526 HW 6"
author: "Satoshi Ido (ID: 34788706)"
date: 4 April 2023
output: pdf_document
---

```{r setup, include = FALSE, cache = FALSE}
knitr::opts_chunk$set(
    echo = TRUE,
    warning = FALSE,
    message = FALSE)
```

```{r}
library("MASS")
library("lmtest")
library("dplyr")
library("data.table")
```

# Problem1
## data
```{r}
data(minn38, package = "MASS")
head(minn38)
```

## analysis
```{r}
options(contrasts = c("contr.treatment", "contr.treatment"))
# fitting proportional odds model, cases weighted by frequency
# no-interaction
m0 <- polr(hs ~ fol + sex, data = minn38, weights = f, Hess = TRUE)
# interaction
m1 <- polr(hs ~ fol * sex, data = minn38, weights = f, Hess = TRUE)
```

# Problem2
## data
```{r}
data(quine, package = "MASS")
df <- quine
head(df)
```

## analysis
```{r}
# fitting gamma regression model with replacing the zero counts with other small numbers

for (i in c(0.01, 0.05, 0.10)) {
    print(paste("replace 0 counts with: ", i))

    df$Days[df$Days == 0] = i
    m2 <- glm(Days ~ Eth + Sex + Age + Lrn, 
            family = Gamma(link = "log"), data = df
            )
    m2_a <- step(m2, list(lower = ~., upper = ~.^3), k = log(146))
    m2_b <- drop(m2_a)
    print(m2_a); print(m2_b)

    # just in case
    print("check the drop")
    m2_c <- update(m2_a, ~. - Sex)
    m2_d <- update(m2_a, ~. - Age)
    m2_e <- update(m2_a, ~. - Lrn)
    m2_f <- update(m2_a, ~. - Eth)
    print(m2_c); print(m2_d); print(m2_e); print(m2_f)
    plot(m2_a)
}

m2_f <- update(m2_a, ~. - Eth + )
```

### further comparison with lrtest
```{r}
print("check the drop")
m2_c <- update(m2_a, ~. - Sex - Lrn)
m2_d <- update(m2_a, ~. - Age - Eth)
lrtest(m2_a, m2_c)
lrtest(m2_a, m2_d)
```

## comparing with negative binomial model and log-normal model
```{r}
# negative binomial model
data(quine, package = "MASS")
df <- quine
m3 <- glm.nb(Days ~ Eth + Sex + Age + Lrn, data = df)
m3_a <- step(m3, list(lower = ~ ., upper = ~.^3))

# log-normal model
df$Days[df$Days == 0] = 0.05
m4 <- glm(log(Days) ~ Eth + Sex + Age + Lrn, data = df)
m4_a <- step(m4, list(lower = ~., upper = ~.^3))
residuals(m4_a, type = c("deviance", "pearson"))
```

```{r}
lrtest(m2_a, m3_a)
summary(m4_a)
m4_a$residuals
```