---
title: "chpt-13"
author: "Satoshi Ido"
date: "11/15/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## パッケージのインストール
```{r}
#install.packages("Rcmdr")
#install.packages("FactoMineR")
#install.packages("dummies")
```

## 「メーカー」「ブランド力」「技術力」の3重クロス集計表
```{r}
#データの読み込み
b3dat <- read.csv("自転車データ3.csv", row.names=1)  #row.names=1にして1変数（評価者番号）を行名にしている
```

### 三重クロス集計表の作成
```{r}
xtabs(~メーカー+ブランド力+技術力, data=b3dat) 
```

## コレスポンデンス分析
### 「自転車データ2.csv」
```{r}
b2dat <- read.csv("自転車データ2.csv", row.names=1) #データの読み込み
b2dat
```

### コレスポンデンス分析の実行
```{r}
library(FactoMineR)
theme_set(theme_bw(base_family = "HiraKakuProN-W3"))
resb2dat <- CA(b2dat) #コレスポンデンス分析の実行
```

### 固有値の出力
```{r}
resb2dat$eig #この値は平面を構成する各軸（次元,dim）がデータの分散をどの程度説明しているかについて考察する際に利用
```

### 行スコア・列スコアの出力
```{r}
resb2dat$row$coord #行スコアの表示
```

```{r}
resb2dat$col$coord #列スコアの表示
```

### 関数summaryの出力
```{r}
summary(resb2dat)
```

## クラスター分析の併用
### メーカーのクラスター分析
```{r}
z <- scale(b2dat) #列方向にz得点化

#平方ユークリッド距離
DO <- dist(z, method="euclidean")
D <- (1/2)*DO^2 

#階層クラスター分析
resclust <- hclust(D, method="ward.D")
plot(resclust) #デンドログラムの描画
```

### クラスターの解釈
```{r}
clus <- cutree(resclust, k=2) #クラスター番号の取得
clus
```
```{r}
b2dat$cluster <- clus
by(b2dat[,-6], b2dat$cluster, apply, 2, mean) #クラスター別の平均値の算出
```

## 多重コレスポンデンス分析
### データ行列の変換
```{r}
library(dummies) #パッケージdummiesの読み込み
db3dat <- dummy.data.frame(b3dat, sep=":") #関数dummy.data.frameの実行
head(db3dat)
```
### CAによる（多重）コレスポンデンス分析の実行
```{r}
resdb3dat <- CA(db3dat)
resdb3dat$eig #固有値の出力の一部 #累積寄与率が2軸まででたった22.021%しかないが、解釈の関係として仕方ない
```

### 多重コレスポンデンスのバイプロット図出力の工夫
```{r}
plot(resdb3dat, invisible="row") #視認性の関係から列カテゴリ（観点）のみをプロット
#plotplot(resdb3dat, invisible="col") #こうすると行カテゴリ（評価者）のみのプロットとなる
```

## ダミーデータ行列を使ったCA関数以外で多重コレスポンデンス分析を実行
```{r}
resb3dat <- MCA(b3dat) #関数MCAによるコレスポンデンス分析の実行(1)
```
### 多重クロス集計表の形式で保存されているオブジェクトに対して多重コレスポンデンス分析を実行する方法
```{r}
#データフレームへ変換
#多重クロス集計表の作成
crosb3dat <- xtabs(~メーカー+ブランド力+コスパ+技術力+レース実績+デザイン, data=b3dat)
#データフレームへの変換
crosdf <- as.data.frame(crosb3dat)
crosdf
```

```{r}
#度数が0のセルを除外
crosdf2 <- subset(crosdf,Freq>=1)
nrow(crosdf2) #数を確認
```

```{r}
#MCAによる多重コレスポンデンス分析の実行(2)
rescrosdf2 <- MCA(crosdf2, quanti.sup=7, row.w=crosdf2$Freq)
```

## コレスポンデンス分析の理論
```{r}
#表13.1に対するコレスポンデンス分析の出力
b2dat2 <- b2dat[,1:3]
resb2dat2 <- CA(b2dat2)
summary(resb2dat2)
round(dist(rbind(resb2dat2$row$coord, 重心=c(0,0))), 3) #メーカー間のユークリッド距離
```

## 章末演習
```{r}
#問1
exdat <- read.csv("自転車データ練習2.csv")
exdat
#問2
dexdat <- dummy.data.frame(exdat, sep=":") #ダミー行列に変換
#問3
rdexdat <- CA(dexdat) #多重コレスポンデンス
summary(rdexdat) #二軸までで43.615の寄与率
#問4
rexdat <- MCA(exdat)
summary(rexdat)
#問5
aa <- xtabs(~メーカー+ブランド力+コスパ+技術力+レース実績+デザイン, data=exdat)
dfexdat <- as.data.frame(aa)
dfexdat2 <- subset(dfexdat,Freq>=1)
#問6
rdfexdat2 <- MCA(dfexdat2, quanti.sup=7, row.w=crosdf2$Freq)
summary(rdfexdat2)
```














