---
title: "Selection_biased & RCT(chpt-2)"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
# 2.1 回帰分析の導入
### 最初にchpt-1の引き継ぎ
```{r message = FALSE}
# (1) パッケージをインストールする（初回のみ）
# install.packages("broom")

# (2) ライブラリの読み出し
library("tidyverse")
library("broom")

# (3) データの読み込み
email_data <- read_csv("http://www.minethatdata.com/Kevin_Hillstrom_MineThatData_E-MailAnalytics_DataMiningChallenge_2008.03.20.csv")

# (4) 女性向けメールが配信されたデータを削除したデータを作成
male_df <- email_data %>%
  filter(segment != "Womens E-Mail") %>% # 女性向けメールが配信されたデータを削除
  mutate(treatment = ifelse(segment == "Mens E-Mail", 1, 0)) # 介入を表すtreatment変数を追加

# (5) セレクションバイアスのあるデータを作成
## seedを固定
set.seed(1)

## 条件に反応するサンプルの量を半分にする
obs_rate_c <- 0.5
obs_rate_t <- 0.5

## バイアスのあるデータを作成
biased_data <- male_df %>%
  mutate(obs_rate_c =
           ifelse( (history > 300) | (recency < 6) |
                     (channel == "Multichannel"), obs_rate_c, 1),
         obs_rate_t =
           ifelse( (history > 300) | (recency < 6) |
                     (channel == "Multichannel"), 1, obs_rate_t),
         random_number = runif(n = NROW(male_df))) %>%
  filter( (treatment == 0 & random_number < obs_rate_c ) |
            (treatment == 1 & random_number < obs_rate_t) )

```

## 2.1.5 Rによるメールマーケティングデータの分析（回帰編）
```{r}
# バイアスのあるデータでの回帰分析
biased_reg = lm(data = biased_data, formula = spend ~ treatment + history)
summary(biased_reg)

# ライブラリの読み出し
library("broom")

# 指定されたパラメータのみを取り出す（tidyを利用）
(biased_reg_coef <- tidy(biased_reg))
```

# 2.2 回帰分析におけるバイアス
## 2.2.1 共変量の追加による効果への作用
```{r}
# RCTデータでの回帰分析とバイアスのあるデータでの回帰分析の比較
## RCTデータで
rct_reg <- lm(data = male_df, formula = spend~treatment)
(rct_reg_coef <- summary(rct_reg) %>% tidy())

## バイアスのあるデータで
nonrct_reg <- lm(data = biased_data, formula = spend~treatment)
(nonrct_reg_coef <- summary(nonrct_reg) %>% tidy())

# 共変量追加で重回帰分析
nonrct_mreg <- lm(data = biased_data, formula = spend ~ treatment + recency + channel + history)
(nonrct_mreg_coef <- tidy(nonrct_mreg))
```

## 2.2.3 RによるOVBの確認
```{r}
# OVBの確認（broomを利用した場合）
## broom の読み出し
library(broom)

## モデル式のベクトルを用意
formula_vec <- c(spend ~ treatment + recency + channel, # モデルA
             spend ~ treatment + recency + channel + history, # モデルB
             history ~ treatment + channel + recency) # モデルC
## formulaに名前をつける
names(formula_vec) <- paste("reg", LETTERS[1:3], sep = "_")

## モデル式のデータフレーム化
(models <- formula_vec %>% enframe(name = "model_index", value = "formula")) # name・value はカラム名

## まとめて回帰分析を実行
df_models <- models %>% 
  mutate(model = map(.x = formula, .f = lm, data = biased_data)) %>% # formulaに保存された3つの回帰式にlm()を実行
  mutate(lm_result = map(.x = model, .f = tidy)) # modelに保存されている3つの回帰分析のパラメータの推定結果をtidy()でdfに変換

## モデルの結果を整形
df_results <- df_models %>%
  mutate(formula = as.character(formula)) %>% # formulaを文字列として表示できるようにする
  select(formula, model_index, lm_result) %>% 
  unnest(cols = c(lm_result))

## モデルA,B,Cでtreatmentのパラメータを抜き出す
treatment_coef <- df_results %>%
  filter(term == "treatment") %>%
  pull(estimate)

## モデルBからhistoryのパラメータを抜き出す
history_coef <- df_results %>%
  filter(model_index == "reg_B", 
         term == "history") %>%
  pull(estimate)

## OVBの確認
OVB <- history_coef * treatment_coef[3]
coef_gap <- treatment_coef[1] - treatment_coef[2]
OVB  # β_4 * γ_1
coef_gap  # α_1 * β_4
```

## 2.2.7 Post treatment bias
```{r}
# 介入の影響を受けるような変数(=Z・Yどちらとも相関関係のある変数)をモデルに含めた場合、回帰分析の結果が歪む
# visit(サイト来訪){:X}と介入{:Z}の相関
cor_visit_treatment <- lm(data = biased_data, formula = treatment ~ visit + channel + recency + history) %>% 
  tidy()

# visitを購買効果の回帰分析に入れて実行
bad_control_reg <- lm(data = biased_data, formula = spend ~ treatment + channel + recency + history + visit) %>% 
  tidy()
```

# 2.3 回帰分析を利用した探索的な効果検証
```{r message = FALSE}
# install.packages("remotes")
remotes::install_github("itamarcaspi/experimentdatar") # コロンビアで行われた私立学校の学費の割引に関する実験分析の研究のデータ
```

## 2.3.2 Rによる回帰分析の実行
```{r}
# ライブラリとデータの読み込み
library(experimentdatar)
library(broom)
library(tidyverse)
data(vouchers)
vouchers
```

```{r}
# Angrist(2002)のtable 3. bogota 1995の再現
# 回帰式の準備
## 回帰式で使う文字列の準備
formula_x_base <- "VOUCH0"
formula_x_covariate <- "SVY + HSVISIT + AGE + STRATA1 + STRATA2 + STRATA3 + STRATA4 + STRATA5 + STRATA6 + STRATAMS + D1993 + D1995 + D1997 + DMONTH1 + DMONTH2 + DMONTH3 + DMONTH4 + DMONTH5 + DMONTH6 + DMONTH7 + DMONTH8 + DMONTH9 + DMONTH10 + DMONTH11 + DMONTH12 + SEX2"
formula_y <- c("TOTSCYRS","INSCHL","PRSCH_C","USNGSCH","PRSCHA_1","FINISH6","FINISH7","FINISH8","REPT6","REPT","NREPT",
               "MARRIED","HASCHILD","HOURSUM","WORKING3")

## formula_yの各要素に対して共変量を含まない回帰式を作成
base_reg_formula <- paste(formula_y, "~", formula_x_base)
names(base_reg_formula) <- paste(formula_y, "base", sep = "_")

## formula_yの各要素に対して共変量を含む回帰式を作成
covariate_reg_formula <-
  paste(formula_y, "~", formula_x_base, "+", formula_x_covariate)
names(covariate_reg_formula) <-
  paste(formula_y, "covariate", sep = "_")

## モデル式のベクトルを作成
table3_fomula <- c(base_reg_formula, covariate_reg_formula)

## モデル式のベクトルをデータフレーム化する
models <- table3_fomula %>%
  enframe(name = "model_index", value = "formula")

# 回帰分析を実行
## bogota 1995のデータを抽出する
regression_data <- vouchers %>% filter(TAB3SMPL == 1, BOG95SMP == 1)

## まとめて回帰分析を実行
df_models <- models %>%
  mutate(model = map(.x = formula,
                     .f = lm,
                     data = regression_data)) %>%
  mutate(lm_result = map(.x = model, .f = tidy))

## モデルの結果を整形
df_results <- df_models %>%
  mutate(formula = as.character(formula)) %>%
  select(formula, model_index, lm_result) %>%
  unnest(cols = c(lm_result))
```

## 2.3.2 私立学校への通学と割引券の利用についての分析
```{r}
# 通学率と奨学金の利用
using_voucher_results <- df_results %>%
  filter(term == "VOUCH0", 
         str_detect(model_index, "PRSCHA_1|USNGSCH")) %>%
  select(model_index, term, estimate, std.error, p.value) %>%
  arrange(model_index)
using_voucher_results
```
```{r}
# 取り出した効果をggplotで可視化
using_voucher_results %>%
  ggplot(aes(y = estimate, x = model_index)) +
  geom_point() +
  geom_errorbar(aes(ymax = estimate + std.error*1.96,
                    ymin = estimate - std.error*1.96,
                    width = 0.1)) +
  theme(axis.text.x = element_text(angle = 45, hjust = 1),
        plot.title = element_text(hjust = 0.5),
        legend.position = "bottom",
        plot.margin = margin(0.5,1,0.5,1, "cm"))
```

## 2.3.4 割引券は留年を減らしているのか？
```{r}
# 留年の傾向を可視化
## PRSCH_C,INSCHL,FINISH6-8,REPTに対するVOUCH0の効果を取り出す
going_private_results <- df_results %>%
  filter(term == "VOUCH0",
         str_detect(model_index, "PRSCH_C|INSCHL|FINISH|REPT")) %>%
  select(model_index, term, estimate, std.error, p.value) %>%
  arrange(model_index)

## 取り出した効果をggplotで可視化
going_private_results %>%
  filter(str_detect(model_index, "covariate")) %>%
  ggplot(aes(y = estimate, x = model_index)) +
  geom_point() +
  geom_errorbar(aes(ymax = estimate + std.error*1.96,
                    ymin = estimate - std.error*1.96,
                    width = 0.1)) +
  geom_hline(yintercept = 0, linetype = 2) +
  theme(axis.text.x = element_text(angle = 45, hjust = 1),
        plot.title = element_text(hjust = 0.5),
        legend.position = "bottom",
        plot.margin = margin(0.5,1,0.5,1, "cm"))
```
## 2.3.5 性別による効果差
```{r}
# (4) Angrist(2002)のTable.4 & 6 bogota 1995の再現
# table4に使うデータを抜き出す
data_tbl4_bog95 <- vouchers %>%
  filter(BOG95SMP == 1, TAB3SMPL == 1,
         !is.na(SCYFNSH), !is.na(FINISH6), !is.na(PRSCHA_1), 
         !is.na(REPT6), !is.na(NREPT), !is.na(INSCHL), 
         !is.na(FINISH7),!is.na(PRSCH_C), !is.na(FINISH8), !is.na(PRSCHA_2), 
         !is.na(TOTSCYRS), !is.na(REPT)
         ) %>%
  select(VOUCH0, SVY, HSVISIT, DJAMUNDI, PHONE, AGE,
         STRATA1:STRATA6, STRATAMS, DBOGOTA, D1993, D1995, D1997,
         DMONTH1:DMONTH12, SEX_MISS, FINISH6, FINISH7, FINISH8,
         REPT6, REPT, NREPT, SEX2, TOTSCYRS, MARRIED, HASCHILD,
         HOURSUM,WORKING3, INSCHL,PRSCH_C,USNGSCH,PRSCHA_1)

# 女子生徒のみのデータでの回帰分析
regression_data <- data_tbl4_bog95 %>% filter(SEX2 == 0) # 女子生徒のデータだけ取り出す

# まとめて回帰分析を実行
df_models <- models %>%
  mutate(model = map(.x = formula, .f = lm, data = regression_data)) %>%
  mutate(lm_result = map(.x = model, .f = tidy))

# モデルの結果を整形
df_results_female <- df_models %>%
  mutate(formula = as.character(formula),
         gender = "female") %>%
  select(formula, model_index, lm_result, gender) %>%
  unnest(cols = c(lm_result))

# 男子生徒のみのデータでの回帰分析
regression_data <- data_tbl4_bog95 %>% filter(SEX2 == 1) #男子生徒のデータだけ取り出す

# まとめて回帰分析を実行
df_models <- models %>%
  mutate(model = map(.x = formula, .f = lm, data = regression_data)) %>%
  mutate(lm_result = map(.x = model, .f = tidy))

df_results_male <- df_models %>%
  mutate(formula = as.character(formula),
         gender = "male") %>%
  select(formula, model_index, lm_result, gender) %>%
  unnest(cols = c(lm_result))

# 通学傾向への分析結果の可視化
## PRSCHA_1,USNGSCHに対する分析結果を抜き出す
using_voucher_results_gender <- rbind(df_results_male, df_results_female) %>%
  filter(term == "VOUCH0", str_detect(model_index, "PRSCHA_1|USNGSCH")) %>%
  select(gender, model_index, term, estimate, std.error, p.value) %>%
  arrange(gender, model_index) %>%
  filter(str_detect(model_index, "covariate"))

## ggplotによる可視化
using_voucher_results_gender %>%
  filter(str_detect(model_index, "covariate")) %>%
  ggplot(aes(y = estimate, x = model_index)) +
  geom_point() +
  geom_errorbar(aes(ymax = estimate + std.error*1.96,
                    ymin = estimate - std.error*1.96,
                    width = 0.1)) +
  geom_hline(yintercept = 0, linetype = 2) +
  theme(axis.text.x = element_text(angle = 45, hjust = 1),
        plot.title = element_text(hjust = 0.5),
        legend.position = "bottom",
        plot.margin = margin(0.5,1,0.5,1, "cm")) +
  facet_grid(gender ~ .)

# 留年と通学年数への分析結果の可視化
## PRSCH_C,INSCHL,REPT,TOTSCYRS,FINISHに対する分析結果を抜き出す
going_private_results_gender <- rbind(df_results_male, df_results_female) %>%
  filter(term == "VOUCH0",
         str_detect(model_index, "PRSCH_C|INSCHL|REPT|TOTSCYRS|FINISH")) %>%
  select(gender, model_index, term, estimate, std.error, p.value) %>%
  arrange(model_index)

## ggplotによる可視化
going_private_results_gender %>%
  filter(str_detect(model_index, "covariate")) %>%
  ggplot(aes(y = estimate, x = model_index)) +
  geom_point() +
  geom_errorbar(aes(ymax = estimate + std.error*1.96,
                    ymin = estimate - std.error*1.96,
                    width = 0.1)) +
  geom_hline(yintercept = 0, linetype = 2) +
  theme(axis.text.x = element_text(angle = 45, hjust = 1),
        plot.title = element_text(hjust = 0.5),
        legend.position = "bottom",
        plot.margin = margin(0.5,1,0.5,1, "cm")) +
  facet_grid(gender ~ .)

# 上記の分析で女子生徒の学業継続は学力・留年・当選（割引券）との相関関係が小さいことがわかったから、別の要因を探る
# 労働時間に対する分析結果の可視化
## HOURに対する分析結果を抜き出す
working_hour_results_gender <- rbind(df_results_male, df_results_female) %>%
  filter(term == "VOUCH0", str_detect(model_index, "HOUR")) %>%
  select(gender, model_index, term, estimate, std.error, p.value) %>%
  arrange(gender, model_index)

## ggplotによる可視化
working_hour_results_gender %>%
  filter(str_detect(model_index, "covariate")) %>%
  ggplot(aes(y = estimate, x = model_index)) +
  geom_point() 
  geom_errorbar(aes(ymax = estimate + std.error*1.96,
                    ymin = estimate - std.error*1.96,
                    width = 0.1)) +
  geom_hline(yintercept = 0, linetype = 2) +
  theme(axis.text.x = element_text(angle = 45, hjust = 1),
        plot.title = element_text(hjust = 0.5),
        legend.position = "bottom",
        plot.margin = margin(0.5,1,0.5,1, "cm")) +
  facet_grid(. ~ gender)
```














