---
title: "セレクションバイアスとRCT(chpt1)"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# RCTを行なったデータの準備
```{r}
# install.packages("tidyverse")
library("tidyverse")

email_data <- read_csv("http://www.minethatdata.com/Kevin_Hillstrom_MineThatData_E-MailAnalytics_DataMiningChallenge_2008.03.20.csv")

# 女性向けメール関係を削除
male_df = email_data %>%
  filter(segment != "Womens E-Mail") %>%
  # 介入を表すtreatment変数を追加
  mutate(treatment = if_else(segment == "Mens E-Mail", 1, 0))
```

# RCTデータの集計と有意差検定
```{r  message = FALSE}
# 集計
summary_by_segement <- male_df %>%
  group_by(treatment) %>% 
  summarise(conversion_rate = mean(conversion), # グループごとのconversionの平均
            spend_mean = mean(spend), # グループごとのspendの平均
            count = n()) # グループごとのデータ数
```

## 有意差検定（t検定）
```{r}
# 男性向けメールが配信されたグループの購買データ
mens_mail <- male_df %>%
  filter(treatment == 1) %>%
  pull(spend)
# メールが配信されなかったグループの購買データ
no_mail <- male_df %>%
  filter(treatment == 0) %>%
  pull(spend)

# 有意差検定の実行
(rct_ttest = t.test(mens_mail, no_mail, var.equal = TRUE))
```

# バイアスのあるデータによる効果の検証
## バイアスのあるデータの準備
```{r}
# seedを固定する
set.seed(1) 

# 条件に反応するサンプルの量を半分にする
obs_rate_c <- 0.5 
obs_rate_t <- 0.5

# バイアスのあるデータの作成
biased_data = male_df %>%
  mutate(obs_rate_c = if_else(
           (history > 300) | (recency < 6) | (channel == "Multichannel"), obs_rate_c, 1),
         obs_rate_t = if_else(
           (history > 300) | (recency < 6) | (channel == "Multichannel"), 1, obs_rate_t),
         random_number = runif(n = NROW(male_df))) %>%
  filter( (treatment == 0 & random_number < obs_rate_c) | (treatment == 1 & random_number < obs_rate_t))

```

## バイアスのあるデータの集計と有意差の検定
```{r message = FALSE}
# 集計
summary_by_segment_biased <- biased_data %>%
  group_by(treatment) %>%
  summarise(conversion_rate = mean(conversion),
            spend_mean = mean(spend),
            count = n())
```

## 有意差検定（t検定）
```{r}
# 男性向けメールが配信されたグループの購買データ
mens_mail_biased <- biased_data %>%
  filter(treatment == 1) %>%
  pull(spend)

# メールが配信されなかったグループの購買データ
no_mail_biased <- biased_data %>%
  filter(treatment == 0) %>%
  pull(spend)

# 平均の差の有意差検定
(rct_ttest_biased = t.test(mens_mail_biased, no_mail_biased, var.equal = T))
```















