---
title: "chpt-11"
author: "Satoshi Ido"
date: "10/11/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## データの読み込み
```{r}
aks <- read.csv("空き巣調査.csv") #データの読み込み
aks$空き巣01 <- ifelse(aks$空き巣=="あり", 1, 0)
aks$セキュリティ01 <- ifelse(aks$セキュリティ=="加入", 1, 0)
aks$飼い犬01 <- ifelse(aks$飼い犬=="あり", 1, 0)
aks[800,]
```

## ロジスティック回帰分析の実行
```{r}
aks.out <- glm(空き巣01~不在時間+会話+築年数+セキュリティ01+飼い犬01, family='binomial', data = aks)
summary(aks.out) #回帰分析の出力表示
```

## 係数・切片を指数変換して算出（解釈が容易になる）
```{r}
exp(aks.out$coefficients)
```

## 係数・切片に関する信頼区間の算出
```{r}
confint(aks.out, level=0.95)
exp(confint(aks.out, level=0.95))
```
## 標準化係数の算出と解釈
```{r}
#自作関数
LRAstdcoef <- function(glm.out, vname){ #glm.out-関数glmによる出力オブジェクト, vname-標準化する量的な説明変数名
  #vnameに指定された変数のみからなるデータフレーム
  subdat <- (glm.out[["data"]])[ , vname]
  #subdatの各変数の標準偏差
  SDs <- apply(subdat, 2, sd)
  #標準化前の推定値
  rawcoef <- (glm.out[["coefficients"]])[vname]
  #標準化後の推定値
  stdcoef <- rawcoef * SDs #推定値に標準偏差をかけるのはなぜ
  return(stdcoef)
}

LRAstdcoef(aks.out, c("不在時間","会話","築年数"))
```

## 回帰モデル評価
```{r}
#Hosmer-Lemeshowの適合度検定
#install.packages('ResourceSelection')
library(ResourceSelection)
hoslem.test(x=aks.out$y, y=fitted(aks.out)) #p値が0.1459より有意でないのでモデルは不適合であるとは言えず、当てはまっていると解釈する
```
## 予測の良さの評価指標の出力と解釈
```{r}
extractAIC(aks.out) #AIC
extractAIC(aks.out, k=log(nrow(aks.out$data))) #BIC、#自然対数変換したもの
```

# その他3つの有益な指標
## 説明変数群の有効性の確認（個々の説明変数の有効性を検討する前提として調べる）
```{r}
aks.out_null <- glm(空き巣01~1, family = 'binomial', data=aks) #切片だけのモデル
anova(aks.out_null, aks.out, test='Chisq') #χ^2検定のP値より説明変数郡による目的変数の説明・予測が有効である
```

## 変数選択
```{r}
step(aks.out_null, direction = 'both',
     scope = ('~不在時間+会話+築年数+セキュリティ01+飼い犬01'))
```

## 多重共線性
```{r}
#install.packages("car")
#install.packages('tibble')
library(car)
library(tibble)
vif(aks.out)
```

## 章末問題
### 問1
```{r}
sks <- read.csv("資格試験.csv")
sks$試験結果01 <- ifelse(sks$試験結果=="合格", 1, 0)
sks$祈願01 <- ifelse(sks$祈願=="あり", 1, 0)
head(sks)
```
### 問2（ロジスティック回帰分析の実行）
```{r}
sks.out <- glm(試験結果01~勉強時間+祈願01+年齢, family='binomial', data = sks)
summary(sks.out) #回帰分析の出力表示
#年齢以外の説明変数は5%有意水準で有効
```

### 問3（切片と係数の指数変換）
```{r}
exp(sks.out$coefficients)
```

### 問4（標準化係数の値とその指数変換値を求める）
```{r}
exp(LRAstdcoef(sks.out, c("勉強時間", "年齢")))
```

### 問5（Hosmer-Lemeshowの適合度検定）
```{r}
library(ResourceSelection)
hoslem.test(x=sks.out$y, y=fitted(sks.out)) #不適合とは言えず、モデルが当てはまっていると考えられる
```
### 問6（多重共線性について）
```{r}
#install.packages("car")
#install.packages('tibble')
library(car)
library(tibble)
vif(sks.out) #多重共線性の可能性は低い
```

