---
title: Final Project 527"
author: "Satoshi Ido, Shu-Ming Meng, Robert Jung"
date: 16 April 2023
output: pdf_document
---
```{r setup, include = FALSE, cache = FALSE}
knitr::opts_chunk$set(
    echo = TRUE,
    warning = FALSE,
    message = FALSE)
```

# library
```{r}
library("MASS")
library("lmtest")
library("dplyr")
library("data.table")
library("stringi")
library("openxlsx")
library("ggplot2")
library("lattice")
library("epiDisplay")
library("car")
library("treemap")
library("d3treeR")
```

# import the dataset
```{r}
print(getwd())
df <- read.csv("/Users/satoshiido/Documents/statistical-analysis/Purdue_STAT527/unicorn_data.csv")
head(df)
```

# preprocess
clean the data
```{r}
cleaner <- function(x){
    # delete the unncessary columns
    x <- subset(
        x,
        select = -c(
            Investors, Portfolio.Exits, Entrepreneur,
            Final.Degree, Final.School)
        )
    # remove the $ and M signs and convert character into numeric
    FUN <- function(y){
            stri_replace_all_regex(y, pattern = c("[$]", "[M]"),
            replacement = c("", ""), vectorize = FALSE)
            }
    cols = c("Valuation.Billion", "Total.Raised.Million")
    x[, cols] <- lapply(x[, cols], FUN)
    x %>% mutate_at(cols, as.numeric) -> x
    # change string to date format
    x$Date.Joined <- as.Date(x$Date.Joined, format = "%m/%d/%Y")
    # return the list of Investors given delimited strings
    x$Select.Inverstors <- strsplit(x$Select.Inverstors, split = ", ")
    return(x)
    }

df <- cleaner(df)
```


## divide into subgroup
```{r}
# Growing IND
growing_list <- c("Artificial Intelligence", "Cybersecurity",
        "Data management & analytics", "Edtech", "Fintech",
        "E-commerce & direct-to-consumer"
        )
df_GI <- df[which(df$Industry %in% growing_list), ]

# Legacy IND
legacy_list <- c("Auto & transportation","Consumer & retail","Hardware",
            "Health","Supply chain, logistics, & delivery","Travel",
            "Internet software & services","Mobile & telecommunications"
            )
df_LI <- df[which(df$Industry %in% legacy_list), ]
```

# visualization
## industry
```{r}
# frequency barchart
tab1(df$Industry, cum.percent = TRUE)
# founded year barchart
barplot(table(df$Founded.Year))
```

## top 5 countries
```{r}
# group by country and count the number of each country
tmp <- df %>%
    group_by(Country) %>%
    summarise(total.country.count = n(), .groups = "drop")
# pick the top 5 countries which produce the unicorn the most
top5countries <- unlist(tmp[order(tmp$total.country.count, decreasing = TRUE), ][0:5, 1])
tmp <- df[which(df$Country %in% top5countries), ] %>%
    group_by(Country) %>%
    summarise(total.value.Billion = sum(Valuation.Billion), .groups = "drop") %>%
    as.data.frame()

# plot
ggplot(
        tmp,
        aes(x = reorder(Country, -total.value.Billion),
        y = total.value.Billion)) +
    geom_bar(stat = "identity", fill = "skyblue4") +
    labs(
        title = "Top 5 countries producing unicorn companies values",
        x = "Country",
        y = "Total.value(B)") +
    theme(
        plot.title = element_text(size = 12, hjust = 0.5, color = "gray25"),
        axis.title.x = element_text(size = 10, hjust = 0.5, color = "gray25"),
        axis.title.y = element_text(size = 10, hjust = 0.5, color = "gray25")
        )

```

## top 10 cities
```{r}
# group by city and count the number of each city
tmp <- df %>%
    group_by(City) %>%
    summarise(total.city.count = n(), .groups = "drop")
# pick the top 10 cities which produce the unicorn the most
top10cities <- unlist(tmp[order(tmp$total.city.count, decreasing = TRUE), ][0:10, 1])
tmp <- df[which(df$City %in% top10cities), ] %>%
    group_by(City) %>%
    summarise(total.value.Billion = sum(Valuation.Billion), .groups = "drop") %>%
    as.data.frame()

# plot
ggplot(
        tmp,
        aes(x = reorder(City, -total.value.Billion),
        y = total.value.Billion)) +
    geom_bar(stat = "identity", fill = "skyblue4") +
    labs(
        title = "Top 10 cities producing unicorn companies values",
        x = "City",
        y = "Total.value(B)") +
    theme(
        plot.title = element_text(size = 12, hjust = 0.5, color = "gray25"),
        axis.title.x = element_text(size = 10, hjust = 0.5, color = "gray25"),
        axis.title.y = element_text(size = 10, hjust = 0.5, color = "gray25"),
        axis.text.x = element_text(size = 8, angle = 60, vjust = 0.7, hjust = 0.7)
        )

```

## treemap by country and industry
```{r}
# basic treemap
p <- treemap(df,
            index = c("Country", "Industry", "Company"),
            type = "index",
            vSize = "Valuation.Billion",
            fontcolor.labels=c("gray", "orange"),
            fontsize.title = 14,
            fontsize.labels = c(12, 10),
            palette = "Set1",
            bg.labels = c("transparent"),
            align.labels = list(
              c("center", "center"),
              c("right", "bottom")
            ),
            title = "Valuation by Country&Industry",
            overlap.labels = 0.5,
            inflate.labels = F
          )
p
# make it interactive ("rootname" becomes the title of the plot):
# inter <- d3tree2(p,  rootname = "Valuation by Country&Industry")

# save the widget
# library("htmlwidgets")
# saveWidget(inter, file = paste0(getwd(), "/HtmlWidget/treemap.html"))
```

```{r}
group <- c(rep("group-1",4),rep("group-2",2),rep("group-3",3))
subgroup <- paste("subgroup" , c(1,2,3,4,1,2,1,2,3), sep="-")
value <- c(13,5,22,12,11,7,3,1,23)
data <- data.frame(group,subgroup,value)
```

# Other visualization
## 1.industry vs founded year
```{r}
df$Count <- rep(1, length(df$Company))

ggplot(
    data=df, aes(x=Founded.Year, y=Count, fill=Industry))+
    geom_bar(position = "stack", stat="identity")+
    theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1))

ggplot(
    data=df_GI,
    aes(x=Founded.Year, y=Valuation.Billion, fill=Industry))+
    geom_bar(position = "stack", stat="identity")+
    theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1)
    )

ggplot(
    data=df_LI,
    aes(x=Founded.Year, y=Valuation.Billion, fill=Industry))+
    geom_bar(position = "stack", stat="identity")+
    theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1)
    )
```

## 2. city vs industry
```{r}
### narrow down the most popular cities for unicorn companies
# head(table(df$City))
# table(df$City)[which(table(df$City) > 5)]
popular_city <- names(table(df$City)[which(table(df$City) > 5)])
# new_df <- subset(df, count(df$City)[2] > 5)
new_df <- subset(df, df$City %in% popular_city)

ggplot(
    data = new_df, aes(x = reorder(City, +Count), y = Count, fill = Industry)) +
    geom_bar(position = "stack", stat = "identity") +
    theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust = 1))
```

## 3.investors
```{r}
# create the matrix of investors frequency count
words.freq <- table(unlist(df$Select.Inverstors))
investors <- cbind(names(words.freq), as.integer(words.freq))
head(investors, 5)

# investors
investors <- as.data.frame(investors)
investors$V2 <- as.numeric(investors$V2)
colnames(investors) <- c("investors", "count")
investors <- investors[order(investors$count, decreasing = TRUE), ]
head(investors, 3)
```


## 4.investors.Count vs valuation.Billion
```{r}
# scatter plot
## Growing IND
plot(x = df_GI[df_GI$Valuation.Billion > 5, ]$Investors.Count,
     y = df_GI[df_GI$Valuation.Billion > 5, ]$Total.Raised.Million,
        pch = 19,
        col = factor(df_GI$Industry),
        xlab = "Investors.Count",
        ylab = "Valuation.Billion"
        )

## Legacy IND
plot(x = df_LI[df_LI$Valuation.Billion > 5, ]$Investors.Count,
     y = df_LI[df_LI$Valuation.Billion > 5, ]$Total.Raised.Million,
        pch = 19,
        col = factor(df_LI$Industry),
        xlab = "Investors.Count",
        ylab = "Valuation.Billion"
        )

ggplot(
    data = new_df, aes(
        x = Investors.Count, y = Valuation.Billion, fill = Industry)) +
    geom_bar(position = "stack", stat = "identity") +
    theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust = 1)
    )

plot(
    sort(df$Investors.Count),
    df$Valuation.Billion,
    col = rgb(0.2, 0.1, 0.5, 0.9),
    type = "l", lwd = 1,
    xlab = "Investors.Count", ylab = "Valuation.Billion",
    pch = 20
    )

polygon( 
  c(min(df$Investors.Count), sort(df$Investors.Count) , max(df$Investors.Count)), 
  c(min(df$Valuation.Billion), df$Valuation.Billion , min(df$Valuation.Billion)), 
  col = rgb(0.2,0.1,0.5,0.2) , border = F
)
qqnorm(df$Investors.Count, frame = F)
qqline(df$Investors.Count, col = "steelblue", lwd = 2)
```

## 5.Valuation vs total.raised
```{r}
# scatter plot
## Growing IND
plot(y = df_GI[(df_GI$Valuation.Billion > 5) & ((df_GI$Valuation.Billion < 90)), ]$Valuation.Billion,
     x = df_GI[(df_GI$Valuation.Billion > 5) & ((df_GI$Valuation.Billion < 90)), ]$Total.Raised.Million,
        pch = 40,
        col = factor(df_GI$Industry),
        xlab = "Investors.Count",
        ylab = "Valuation.Billion"
        )
```
