---
title: "STAT 527 HW 6"
author: "Satoshi Ido (ID: 34788706)"
date: 27 February 2023
output: pdf_document
---
```{r setup, include = FALSE, cache = FALSE}
knitr::opts_chunk$set(
    echo = TRUE,
    warning = FALSE,
    message = FALSE)
```

```{r}
library("devtools")
library("roxygen2")

# set the path for the working directory
setwd("/Users/satoshiido/Documents/statistical-analysis/Purdue_STAT527")

# A folder named myknapsack will be created
devtools :: create("myknapsack")

# change the working directory to my R package project
setwd("./myknapsack")

# Copy my Knapsack() function from HW5 into an empty R script file named Knapsack.R and save it under the directory ./R/ in my project folder

# .Rd files will be automatically created under the directory ./man/.
document()

# Prepare the required data
## Save the test values wt, vt, W into a list named mydata
wt <- c(10, 20, 30)
vt <- c(60, 100, 120)
w <- 50
mydata <- list(wt, vt, w)
## A new folder named data will be created, under which the data file mydata.rda is stored
use_data(mydata)


```