---
title: "STAT 527 HW 8"
author: "Satoshi Ido (ID: 34788706)"
date: 10 April 2023
output: pdf_document
---
```{r setup, include = FALSE, cache = FALSE}
knitr::opts_chunk$set(
    echo = TRUE,
    warning = FALSE,
    message = FALSE)
```

```{r}
library("stringr")
# get the data from R file
# source("Purdue_STAT527/hw8.R")
```

```{r}
## Q1
v1 <- "The sun was shining on the sea. Sally saw the seagulls and smiled."
## Q2
v2 <- c("apple", "banana", "123", "456", "grape", "789", "orange", "melon")
## Q3
v3 <- "The cat sat on the mat. The cat slept well."
## Q4
v4 <- c("jane.doe@example.com", "john_smith@company.co.uk", "info@myblog.com",
        "james.bond@mi6.gov.uk", "support@amazon.com", "not_an_email_address",
        "user@localhost", "example.com", "myemail@com"
        )
## Q5
v5 <- c("1-800-555-1234", "555-123-4567", "(555) 555-7890", "123-456-7890",
        "555.555.1212", "1112223333", "123", "456-789-0123", "555/123-4567"
        )
```

# Q1
```{r}
# extract all the words that start with “s” from the sentence
str_extract_all(v1, "(?<=\\b)s[^\\s]+")
```

# Q2
```{r}
# extract all the numbers from the given vector
x <- as.numeric(gsub(".*?([0-9]+).*", "\\1", v2))
x[!is.na(x)]
```

# Q3
```{r}
# replace all the occurrences of “cat” with “dog” in the given sentence
gsub("cat", "dog", v3)
```

# Q4
```{r}
# extract all the email addresses from the given vector
y <- str_match(v4, "^[[:alnum:]|[._%+]._-]+@[[:alnum:]|[-.]-.]+\\.+[[:alpha:]]{2,}+$")
y[!is.na(y)]
```

# Q5
```{r}
# extract all the phone numbers in the given vector
z <- str_match(v5, "\\(?\\d{3}\\)?[.-]? *\\d{3}[.-]? *[.-]?\\d{4}")
z[!is.na(z)]
```